version: '3.9'

services:
  
  auth-service:
    container_name: auth-service
    build: .
    ports:
      - "8081:8081"
      - "8085:8085"
    networks:
      - global-network

networks:
  global-network:
    external: true
    name: global-network
    driver: bridge

volumes:
  db:
  redis-data:
    driver: local
